### ISSUE TITLE
KaTeX released 0.12.0

### ISSUE THREAD

**Issue by centixkadon** [glebm/katex-ruby#3]
KaTeX had released version 0.12.0, and add some features like display mode support for MathML.

https://github.com/KaTeX/KaTeX/releases/tag/v0.12.0

Please help if possible.

**Comment by mwt** [comment]
I have a fork that is upgraded to v0.13.3 #5

**Comment by glebm** [comment]
Pushed a new version to rubygems, thanks @mwt!
